# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
# The stack name for the deployment. This should be unique for each deployment.
# We will use a generic name here, but in a real-world scenario, you might want to parameterize this.
stack_name = "aimon-backend-api-dev"

[default.build.parameters]
cached = true
parallel = true
use_container = true # Added to ensure builds happen in a container, which is good practice for Lambda

[default.validate.parameters]
lint = true

[default.deploy.parameters]
# CAPABILITY_IAM is required because we are creating IAM roles for Lambda functions.
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "aimon-backend-api-dev" # Specify an S3 prefix for deployment artifacts
region_name = "us-east-1" # Specify your desired AWS region

# Parameters for specific functions (if needed, but template.yaml handles most of this)
# For example, if you had parameters in template.template.yaml that needed values:
# parameter_overrides = { UsersTableName = "MyCustomUsersTable", SessionsTableName = "MyCustomSessionsTable" }

[default.package.parameters]
resolve_s3 = true
s3_prefix = "aimon-backend-api-dev" # Specify an S3 prefix for deployment artifacts
region_name = "us-east-1" # Specify your desired AWS region

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"