name: CI-DynamoDB

on:
  push:
    branches:
      - main

jobs:
  deploy-dynamodb-tables:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        table: [UsersTable, QuizGroupsTable, QuestionsTable, ScoresTable, ResourcesTable, SessionsTable]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install, Build, Test, and Deploy ${{ matrix.table }}
        working-directory: ./backend/iac/dynamodb/${{ matrix.table }}
        run: |
          npm ci
          npm run build
          npm run test
          npm run cdk -- deploy --require-approval never