# Deploy Lambda Functions
name: Deploy Lambda Functions

on:
  push:
    branches: [ main,develop ] # mainブランチへのプッシュでこのワークフローが実行されます
    paths:
      - '.github/workflows/ci-lambda.yml'
      - 'backend/src/**'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest # ジョブを実行するランナーを指定

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4 # リポジトリのコードをチェックアウト
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Print current directory and list files
        run: |
          pwd
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Node.js環境をセットアップ
        with:
          node-version: '22.x'

      - name: Install SharedLogicLayer Dependencies
        run: npm install
        working-directory: ./backend/src/nodejs

      - name: Install Lambda Function Dependencies
        run: |
          cd ./backend/src/lambda/
          
          # Install dependencies for each Lambda function
          for dir in */; do
            if [ -f "${dir}package.json" ]; then
              echo "Installing dependencies for ${dir}"
              cd "${dir}"
              npm install
              cd ..
            fi
          done
          
          # Install AWS SDK dependencies globally in lambda directory
          npm install @aws-sdk/client-dynamodb
          npm install @aws-sdk/lib-dynamodb

      - name: Build SAM Application
        run: sam build -t ./backend/src/lambda/template.yaml

      - name: Deploy SAM Application
        env:
          CLOUD_FRONT_API_SECRET_VALUE: ${{ secrets.CLOUD_FRONT_API_SECRET_VALUE }}
          ENV_PREFIX: ${{ secrets.ENV_PREFIX }}
          APP_BUCKET_NAME: ${{secrets.APP_BUCKET_NAME}}
          CONTENTS_BUCKET_NAME: ${{secrets.contents_bucket_name}}
          APP_BASE_PATH: ${{secrets.APP_BASE_PATH}}
          ENABLE_BASIC_AUTH: ${{secrets.ENABLE_BASIC_AUTH}}
          ENABLE_WAF: ${{secrets.ENABLE_WAF}}
        run: sam deploy --region ap-northeast-1 --stack-name aimon-${ENV_PREFIX} --no-confirm-changeset --no-fail-on-empty-changeset --config-file ./backend/src/lambda/samconfig.toml --parameter-overrides "ContentsBucketName=${CONTENTS_BUCKET_NAME} AppBucketName=${APP_BUCKET_NAME} AppBasePath=${APP_BASE_PATH} CloudFrontSecretHeaderValue=${CLOUD_FRONT_API_SECRET_VALUE} EnvPrefix=${ENV_PREFIX} UsersTableName=${ENV_PREFIX}UsersTable SessionsTableName=${ENV_PREFIX}SessionsTable ScoresTableName=${ENV_PREFIX}ScoresTable ResourcesTableName=${ENV_PREFIX}ResourcesTable QuizGroupsTableName=${ENV_PREFIX}QuizGroupsTable QuestionsTableName=${ENV_PREFIX}QuestionsTable AimonSecretName=ai-mon-secret EnableBasicAuth=${ENABLE_BASIC_AUTH} EnableWAF=${ENABLE_WAF}"
