name: Deploy frontend-s3 to S3

on:
  push:
    branches:
      - main # mainブランチへのプッシュ時にトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest # ジョブを実行するランナーを指定
    permissions:
      id-token: write # OIDC を使用するために必要
      contents: read # コードをチェックアウトするために必要

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # リポジトリのコードをチェックアウト

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # 必要に応じてセッショントークンも指定
          aws-region: ap-northeast-1 # ここにバケットを作成したいAWSリージョンを指定してください (例: ap-northeast-1)
          role-to-assume: ${{secrets.AWS_S3_ROLE}}

      - name: Create S3 bucket if it doesn't exist
        run: |
          aws s3 ls s3://${{secrets.contents_bucket_name}}-${{ secrets.ENV_PREFIX }} || aws s3 mb s3://${{secrets.contents_bucket_name}}-${{ secrets.ENV_PREFIX }} --region ap-northeast-1 # ここもリージョンを合わせてください

       # - name: Set bucket policy for CloudFront access
        #run: |
        #   aws s3api put-bucket-policy --bucket ${{ github.event.inputs.bucket_name || 'ai-mon-contents-files' }} --policy '{"Version": "2012-10-17", "Statement": [{"Sid": "AllowCloudFrontPublicRead", "Effect": "Allow", "Principal": {"AWS": "*"}, "Action": ["s3:GetObject"], "Resource": ["arn:aws:s3:::${{ github.event.inputs.bucket_name || 'ai-mon-contents-files' }}/*"]}]}' --region ap-northeast-1
        # env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          # role-to-assume: ${{secrets.AWS_S3_ROLE}}

      - name: Sync frontend-s3 directory to S3 bucket
        run: aws s3 sync ${{secrets.LOCAL_FRONTEND_S3}} s3://${{secrets.contents_bucket_name}}-${{ secrets.ENV_PREFIX }} --delete # frontend-s3 ディレクトリを同期し、不要なファイルは削除
